name: bash script job

on:
  push:
    branches: [main]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash script
        run: chmod +x ./.github/workflows/bash-script.sh
             
        shell: bash
