name: bash script job

on:
  push:
    branches: [main]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash script
        run: sudo ln -snf /bin/env /usr/bin/bash 
             bash-scrip.sh
        shell: bash
