name: Execute Bash Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Execute script
      run: bash eorPublish.sh
