name: bash script job

on:
  push:
    branches: [main]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash script
        run: sudo apt-get update
             sudo apt-get install bash
             bash-scrip.sh
        shell: bash
